version: '2'

services:
  api:
    build: ./api
    expose:
      - "8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    volumes:
      - ./api/:/usr/src/app/api
    command: flask run --host=0.0.0.0 --port 8000
